NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls'))
]

NewsPaper/news/urls.py
from django.urls import path
from .views import News, PostList, Search, PostCreate, PostEdit, PostDelete
app_name = 'news'
urlpatterns = [
    path('', News.as_view(), name='post_list'),
    path('<int:pk>/', PostList.as_view(), name='post'),
    path('search/', Search.as_view(), name='post_search'),
    path('add/', PostCreate.as_view(), name='post_add'),
    path('<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
]

NewsPaper/accounts/models.py
from django.db import models

# Create your models here.

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db.models import Sum
# Create your models here.

class Author(models.Model):
    ratingAuthor = models.IntegerField(default = 0)
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)

    def update_rating(self):

        postRat = self.post_set.all().aggregate(ratingPost = Sum('ratingPost'))
        pRat = 0
        pRat += postRat.get('ratingPost')

        commentRat = self.authorUser.comment_set.all().aggregate(ratingComment = Sum('ratingComment'))
        cRat = 0
        cRat += commentRat.get('ratingComment')

        commentPostRat = Comment.objects.filter(commentPost__author = self).values('ratingComment').aggregate(ratingComment = Sum('ratingComment'))
        cPRat = 0
        cPRat += commentPostRat.get('ratingComment')

        # print('pRat =', pRat * 3, 'cRat = ', cRat, 'cPRat = ', cPRat)

        self.ratingAuthor = pRat * 3 + cRat + cPRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'

class Category(models.Model):
    category = models.CharField(max_length = 255, unique = True)

class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    TYPE_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    type = models.CharField(max_length = 2, choices = TYPE_CHOICES, default = ARTICLE)
    timePost = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length = 255)
    textPost = models.TextField()
    ratingPost = models.IntegerField(default=0)

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.ratingPost += 1
        self.save()

    def dislike(self):
        self.ratingPost -= 1
        self.save()

    def preview(self):
        return self.textPost[:124] + '...'

    def __str__(self):
        return f'{self.title} {self.textPost}'

    def get_absolute_url(self):
        return f'/news/{self.id}'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete = models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete = models.CASCADE)

class Comment(models.Model):
    textComment = models.TextField()
    timeComment = models.DateTimeField(auto_now_add=True)
    ratingComment = models.IntegerField(default=0)

    commentPost = models.ForeignKey(Post, on_delete = models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        try:
            return self.commentPost.author.authorUser.username
        except:
            return self.commentUser.username


    def like(self):
        self.ratingComment +=1
        self.save()

    def dislike(self):
        self.ratingComment -=1
        self.save()



NewsPaper/news/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['type', 'title', 'textPost', 'author']
        labels = {
            'type': 'Нововсть/статья',
            'title': 'Заголовок',
            'textPost': 'Текст новости/статьи',
            'author': 'Автор',
        }
        widgets = {
            'type': forms.Select(attrs={
                'class': 'form-control',
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите заголовок'
            }),
            'textPost': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст вашей нововсти или статьи'
            }),
            'author': forms.Select(attrs={
                'class': 'form-control'
            }),
        }

NewsPaper/accounts/views.py
from django.shortcuts import render

# Create your views here.

NewsPaper/news/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator  # импортируем класс, позволяющий удобно осуществлять постраничный вывод

from .filters import PostFilter
from .forms import PostForm
from .models import Post


class News(ListView):
    model = Post
    template_name = 'news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-timePost')
    paginate_by = 10


class PostList(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'


class Search(ListView):
    model = Post
    template_name = 'search.html'
    queryset = Post.objects.order_by('-timePost')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context



class PostCreate(CreateView):
    template_name = 'post_create.html'
    form_class = PostForm


class PostEdit(UpdateView):
    template_name = 'post_edit.html'
    form_class = PostForm

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDelete(DeleteView):
    template_name = 'post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:post_list')

NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Свежие новости:</h1>

{% for post in news %}
    <h3 > {{ post.title|censor }} </h3>
    <p> {{ post.textPost|censor|truncatewords:20}} </p>
    <a href="/news/{{post.id}}">Читать далее</a>
    <p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }} <a href="{% url 'news:post_edit' post.id %}">Update </a><a href="{% url 'news:post_delete' post.id %}"> Delete</a></p>
{% endfor %}
{% include 'paginator.html' %}
{% endblock content %}

NewsPaper/templates/paginator.html
{% if is_paginated %}

   {% if page_obj.has_previous %}
       <a href="?page=1">First</a>
       <a href="?page={{ page_obj.previous_page_number }}"> <<< </a>
   {% endif %}

   {% for num in page_obj.paginator.page_range %}
       {% if page_obj.number == num %}
           <a>{{ num }}</a>
       {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
           <a href="?page={{ num }}">{{ num }}</a>
       {% endif %}
   {% endfor %}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">>>></a>
       <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
   {% endif %}


{% endif %}

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
News:
{% endblock title %}

{% block content %}
<h3>{{ post.title|censor }}</h3>
<p>{{ post.timePost }}</p>
<p>{{ post.textPost|censor }}</p>
<p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }} <a href="{% url 'news:post_edit' post.id %}">Update </a><a href="{% url 'news:post_delete' post.id %}"> Delete</a></p>
{% endblock content %}

NewsPaper/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post create
{% endblock title %}

{% block content %}

<h3>Создание нововсти или статьи:</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <input class="btn btn-success" type="submit" value="Add">
</form>

{% endblock content %}

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post delete
{% endblock title %}

{% block content %}

<h3>Вы уверены что хотите удалить эту нововсть?</h3>

 <div class="card">
     <h3> {{ post.title|censor }} </h3>
     <p> {{ post.textPost|censor|truncatewords:20}} </p>
     <p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }}</p>
 </div>

<form method="POST">
 {% csrf_token %}
    <input class="btn btn-success" type="submit" value="Да, удалить">
</form>

{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post edit
{% endblock title %}

{% block content %}

<h3>Редактирование новости/статьи:</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <input class="btn btn-success" type="submit" value='Добавить изменения'>
</form>

{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Поиск по новостям:</h1>

<form class="form-label" method="GET">
   {{ filter.form }}
   <input class="btn btn-primary btn-lg" type="submit" value="Найти">
</form>

{% for post in filter.qs %}
    <h3> {{ post.title|censor }} </h3>
    <p> {{ post.textPost|censor|truncatewords:20}} </p>
    <p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }} </p>
{% endfor %}

{% include 'paginator.html' %}

{% endblock content %}